baseURL: "https://nrx221b.github.io/"
title: metanoia
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

homeInfoParams:
    Title: "Hi there!👋"
    Content: >
       Welcome to my Blog!

      - I will post my thoughts & random stuff here.
